name: setup-smplx

inputs:
  revision:
    description: "Commit in repository to use"
    required: false
    default: "master"
  owner-repo:
    description: "Owner repo on Github to use"
    required: false
    default: "BlockstreamResearch/smplx"

runs:
  using: composite
  steps:
    - name: Install smplx-cli via simplexup
      shell: bash
      run: |
        set -euo pipefail
        REVISION="${{ inputs.revision }}"
        OWNER_REPO="${{ inputs.owner-repo }}"
        bash "$GITHUB_WORKSPACE/.github/scripts/setup-smplx" "${REVISION}" "${OWNER_REPO}"
